name: Integration Tests

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: aws-test
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: us-east-1

    - name: Run integration tests
      run: |
        go test ./test/integration/... -v -timeout 30m 