name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Add permission to write PR checks
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run unit tests
      run: |
        # Run only unit tests (skip integration tests)
        go test ./internal/... -v 